# Netlify deployment configuration
[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "22"

# Serverless functions
[functions]
  directory = "netlify/functions"

# Redirects for SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
